// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.5

// Built By: go install

package stores

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// AuthTypeNone is a AuthType of type none.
	AuthTypeNone AuthType = "none"
	// AuthTypeToken is a AuthType of type token.
	AuthTypeToken AuthType = "token"
	// AuthTypeSsh is a AuthType of type ssh.
	AuthTypeSsh AuthType = "ssh"
)

var ErrInvalidAuthType = fmt.Errorf("not a valid AuthType, try [%s]", strings.Join(_AuthTypeNames, ", "))

var _AuthTypeNames = []string{
	string(AuthTypeNone),
	string(AuthTypeToken),
	string(AuthTypeSsh),
}

// AuthTypeNames returns a list of possible string values of AuthType.
func AuthTypeNames() []string {
	tmp := make([]string, len(_AuthTypeNames))
	copy(tmp, _AuthTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x AuthType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AuthType) IsValid() bool {
	_, err := ParseAuthType(string(x))
	return err == nil
}

var _AuthTypeValue = map[string]AuthType{
	"none":  AuthTypeNone,
	"token": AuthTypeToken,
	"ssh":   AuthTypeSsh,
}

// ParseAuthType attempts to convert a string to a AuthType.
func ParseAuthType(name string) (AuthType, error) {
	if x, ok := _AuthTypeValue[name]; ok {
		return x, nil
	}
	return AuthType(""), fmt.Errorf("%s is %w", name, ErrInvalidAuthType)
}

// MarshalText implements the text marshaller method.
func (x AuthType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *AuthType) UnmarshalText(text []byte) error {
	tmp, err := ParseAuthType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x AuthType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errAuthTypeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *AuthType) Scan(value interface{}) (err error) {
	if value == nil {
		*x = AuthType("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseAuthType(v)
	case []byte:
		*x, err = ParseAuthType(string(v))
	case AuthType:
		*x = v
	case *AuthType:
		if v == nil {
			return errAuthTypeNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errAuthTypeNilPtr
		}
		*x, err = ParseAuthType(*v)
	default:
		return errors.New("invalid type for AuthType")
	}

	return
}

// Value implements the driver Valuer interface.
func (x AuthType) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// ProviderGithub is a Provider of type github.
	ProviderGithub Provider = "github"
	// ProviderGitlab is a Provider of type gitlab.
	ProviderGitlab Provider = "gitlab"
	// ProviderGeneric is a Provider of type generic.
	ProviderGeneric Provider = "generic"
)

var ErrInvalidProvider = fmt.Errorf("not a valid Provider, try [%s]", strings.Join(_ProviderNames, ", "))

var _ProviderNames = []string{
	string(ProviderGithub),
	string(ProviderGitlab),
	string(ProviderGeneric),
}

// ProviderNames returns a list of possible string values of Provider.
func ProviderNames() []string {
	tmp := make([]string, len(_ProviderNames))
	copy(tmp, _ProviderNames)
	return tmp
}

// String implements the Stringer interface.
func (x Provider) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Provider) IsValid() bool {
	_, err := ParseProvider(string(x))
	return err == nil
}

var _ProviderValue = map[string]Provider{
	"github":  ProviderGithub,
	"gitlab":  ProviderGitlab,
	"generic": ProviderGeneric,
}

// ParseProvider attempts to convert a string to a Provider.
func ParseProvider(name string) (Provider, error) {
	if x, ok := _ProviderValue[name]; ok {
		return x, nil
	}
	return Provider(""), fmt.Errorf("%s is %w", name, ErrInvalidProvider)
}

// MarshalText implements the text marshaller method.
func (x Provider) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Provider) UnmarshalText(text []byte) error {
	tmp, err := ParseProvider(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x Provider) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errProviderNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Provider) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Provider("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseProvider(v)
	case []byte:
		*x, err = ParseProvider(string(v))
	case Provider:
		*x = v
	case *Provider:
		if v == nil {
			return errProviderNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errProviderNilPtr
		}
		*x, err = ParseProvider(*v)
	default:
		return errors.New("invalid type for Provider")
	}

	return
}

// Value implements the driver Valuer interface.
func (x Provider) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// StatusPending is a Status of type pending.
	StatusPending Status = "pending"
	// StatusRunning is a Status of type running.
	StatusRunning Status = "running"
	// StatusSuccess is a Status of type success.
	StatusSuccess Status = "success"
	// StatusFailed is a Status of type failed.
	StatusFailed Status = "failed"
	// StatusCanceled is a Status of type canceled.
	StatusCanceled Status = "canceled"
)

var ErrInvalidStatus = fmt.Errorf("not a valid Status, try [%s]", strings.Join(_StatusNames, ", "))

var _StatusNames = []string{
	string(StatusPending),
	string(StatusRunning),
	string(StatusSuccess),
	string(StatusFailed),
	string(StatusCanceled),
}

// StatusNames returns a list of possible string values of Status.
func StatusNames() []string {
	tmp := make([]string, len(_StatusNames))
	copy(tmp, _StatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x Status) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Status) IsValid() bool {
	_, err := ParseStatus(string(x))
	return err == nil
}

var _StatusValue = map[string]Status{
	"pending":  StatusPending,
	"running":  StatusRunning,
	"success":  StatusSuccess,
	"failed":   StatusFailed,
	"canceled": StatusCanceled,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	return Status(""), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}

// MarshalText implements the text marshaller method.
func (x Status) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Status) UnmarshalText(text []byte) error {
	tmp, err := ParseStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x Status) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Status) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Status("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseStatus(v)
	case []byte:
		*x, err = ParseStatus(string(v))
	case Status:
		*x = v
	case *Status:
		if v == nil {
			return errStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errStatusNilPtr
		}
		*x, err = ParseStatus(*v)
	default:
		return errors.New("invalid type for Status")
	}

	return
}

// Value implements the driver Valuer interface.
func (x Status) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// StepStatusPending is a StepStatus of type pending.
	StepStatusPending StepStatus = "pending"
	// StepStatusRunning is a StepStatus of type running.
	StepStatusRunning StepStatus = "running"
	// StepStatusSuccess is a StepStatus of type success.
	StepStatusSuccess StepStatus = "success"
	// StepStatusFailed is a StepStatus of type failed.
	StepStatusFailed StepStatus = "failed"
	// StepStatusSkipped is a StepStatus of type skipped.
	StepStatusSkipped StepStatus = "skipped"
	// StepStatusCanceled is a StepStatus of type canceled.
	StepStatusCanceled StepStatus = "canceled"
)

var ErrInvalidStepStatus = fmt.Errorf("not a valid StepStatus, try [%s]", strings.Join(_StepStatusNames, ", "))

var _StepStatusNames = []string{
	string(StepStatusPending),
	string(StepStatusRunning),
	string(StepStatusSuccess),
	string(StepStatusFailed),
	string(StepStatusSkipped),
	string(StepStatusCanceled),
}

// StepStatusNames returns a list of possible string values of StepStatus.
func StepStatusNames() []string {
	tmp := make([]string, len(_StepStatusNames))
	copy(tmp, _StepStatusNames)
	return tmp
}

// String implements the Stringer interface.
func (x StepStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x StepStatus) IsValid() bool {
	_, err := ParseStepStatus(string(x))
	return err == nil
}

var _StepStatusValue = map[string]StepStatus{
	"pending":  StepStatusPending,
	"running":  StepStatusRunning,
	"success":  StepStatusSuccess,
	"failed":   StepStatusFailed,
	"skipped":  StepStatusSkipped,
	"canceled": StepStatusCanceled,
}

// ParseStepStatus attempts to convert a string to a StepStatus.
func ParseStepStatus(name string) (StepStatus, error) {
	if x, ok := _StepStatusValue[name]; ok {
		return x, nil
	}
	return StepStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidStepStatus)
}

// MarshalText implements the text marshaller method.
func (x StepStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *StepStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseStepStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x StepStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errStepStatusNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *StepStatus) Scan(value interface{}) (err error) {
	if value == nil {
		*x = StepStatus("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseStepStatus(v)
	case []byte:
		*x, err = ParseStepStatus(string(v))
	case StepStatus:
		*x = v
	case *StepStatus:
		if v == nil {
			return errStepStatusNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errStepStatusNilPtr
		}
		*x, err = ParseStepStatus(*v)
	default:
		return errors.New("invalid type for StepStatus")
	}

	return
}

// Value implements the driver Valuer interface.
func (x StepStatus) Value() (driver.Value, error) {
	return x.String(), nil
}

const (
	// TriggerManual is a Trigger of type manual.
	TriggerManual Trigger = "manual"
	// TriggerWebhook is a Trigger of type webhook.
	TriggerWebhook Trigger = "webhook"
	// TriggerCron is a Trigger of type cron.
	TriggerCron Trigger = "cron"
	// TriggerRebuild is a Trigger of type rebuild.
	TriggerRebuild Trigger = "rebuild"
)

var ErrInvalidTrigger = fmt.Errorf("not a valid Trigger, try [%s]", strings.Join(_TriggerNames, ", "))

var _TriggerNames = []string{
	string(TriggerManual),
	string(TriggerWebhook),
	string(TriggerCron),
	string(TriggerRebuild),
}

// TriggerNames returns a list of possible string values of Trigger.
func TriggerNames() []string {
	tmp := make([]string, len(_TriggerNames))
	copy(tmp, _TriggerNames)
	return tmp
}

// String implements the Stringer interface.
func (x Trigger) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Trigger) IsValid() bool {
	_, err := ParseTrigger(string(x))
	return err == nil
}

var _TriggerValue = map[string]Trigger{
	"manual":  TriggerManual,
	"webhook": TriggerWebhook,
	"cron":    TriggerCron,
	"rebuild": TriggerRebuild,
}

// ParseTrigger attempts to convert a string to a Trigger.
func ParseTrigger(name string) (Trigger, error) {
	if x, ok := _TriggerValue[name]; ok {
		return x, nil
	}
	return Trigger(""), fmt.Errorf("%s is %w", name, ErrInvalidTrigger)
}

// MarshalText implements the text marshaller method.
func (x Trigger) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Trigger) UnmarshalText(text []byte) error {
	tmp, err := ParseTrigger(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x Trigger) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errTriggerNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *Trigger) Scan(value interface{}) (err error) {
	if value == nil {
		*x = Trigger("")
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case string:
		*x, err = ParseTrigger(v)
	case []byte:
		*x, err = ParseTrigger(string(v))
	case Trigger:
		*x = v
	case *Trigger:
		if v == nil {
			return errTriggerNilPtr
		}
		*x = *v
	case *string:
		if v == nil {
			return errTriggerNilPtr
		}
		*x, err = ParseTrigger(*v)
	default:
		return errors.New("invalid type for Trigger")
	}

	return
}

// Value implements the driver Valuer interface.
func (x Trigger) Value() (driver.Value, error) {
	return x.String(), nil
}
